name: Kotlin Code Style Check

on:
  pull_request:

jobs:
  build:
    name: Android Style Check
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIV_REPO_PAT }}
          submodules: 'recursive'

      - name: Set up JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run spotlessKotlinCheck task
        uses: gradle/gradle-build-action@v2.8.0
        env:
          CI: true
          GHTOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHUSERNAME: ${{ secrets.GHUSERNAME }}
          SIGN_KEY_PW: ${{ secrets.SIGN_KEY_PW }}
          SIGN_STORE_PW: ${{ secrets.SIGN_STORE_PW }}
        with:
          arguments: spotlessKotlinCheck --stacktrace
